# ===== Email settings =====
email_address: example@mail.com
email_password: password_example

# ===== Default arguments =====
time_to_run: 10 # time to run (in minutes)
recipients: client.1@mail.com, client.2@mail.com,
verbose: False

# ===== Inner settings =====
tickets_url: https://hermon.pres.global/ski
closed_keyword: אזל
success_keyword: יש

# time to wait before searching again after finding tickets (in seconds)
wait_after_find: 600
# time to wait before searching again after not finding tickets (in seconds)
wait_after_search: 30

headless: True
