# ===== Email settings =====
email_address: example@mail.com
email_password: password_example

# ===== Inner settings =====
tickets_url: https://hermon.pres.global/vouchers
closed_keyword: אזל
success_keyword: יש

# time to wait before searching again after finding tickets (in seconds)
wait_after_find: 600
# time to wait before searching again after not finding tickets (in seconds)
wait_after_search: 30

# ===== Logger settings =====
# separator for logging
separator: =====